import type { SkillInfo } from './types';

// Only skills with verified, existing GitHub repos.
// IDs match the repo path so settingSources[] works directly with Claude Code CLI.

export const CORE_SKILLS: SkillInfo[] = [
  { id: 'ramziddin/solid-skills', name: 'SOLID + TDD + Clean Code + Architecture', author: 'ramziddin', repo: 'ramziddin/solid-skills', category: 'Engineering', desc: 'SOLID principles, TDD (Red→Green→Refactor), Clean Code, Clean Architecture — all in a single skill', locked: true },
  { id: 'alinaqi/claude-bootstrap', name: 'Spec-Driven Development', author: 'alinaqi', repo: 'alinaqi/claude-bootstrap', category: 'Workflow', desc: 'Spec-driven atomic todos, CLI orchestration, security-first project initialization', locked: true },
  { id: 'fvadicamo/dev-agent-skills', name: 'Git & GitHub Workflow', author: 'fvadicamo', repo: 'fvadicamo/dev-agent-skills', category: 'Workflow', desc: 'Conventional commits, PRs, code review, branching — Git and GitHub skills', locked: true },
];

export const OPTIONAL_SKILLS: SkillInfo[] = [
  // ── Plugin Marketplace ───────────────────────────────────────────────────
  { id: 'anthropics/skills', name: 'Anthropic Official Skills', author: 'anthropics', repo: 'anthropics/skills', category: 'Official', desc: 'Official Anthropic skills for Claude Code', tags: ['official', 'anthropic'], install: 'plugin marketplace' },
  { id: 'obra/superpowers', name: 'Superpowers (20+ skills)', author: 'obra', repo: 'obra/superpowers', category: 'Framework', desc: 'Brainstorming, planning, git worktrees, TDD enforcement, subagent-driven development', tags: ['planning', 'worktrees', 'tdd', 'debugging', 'quality-gates'], install: 'plugin marketplace' },
  { id: 'jpcaparas/superpowers-laravel', name: 'Laravel Superpowers', author: 'jpcaparas', repo: 'jpcaparas/superpowers-laravel', category: 'Framework', desc: 'Laravel-specific superpowers: Eloquent patterns, migrations, Artisan, Blade, testing', tags: ['laravel', 'php', 'eloquent', 'blade'], install: 'plugin marketplace' },
  { id: 'elvismdev/claude-wordpress-skills', name: 'WordPress Performance + Security', author: 'elvismdev', repo: 'elvismdev/claude-wordpress-skills', category: 'CMS', desc: 'WordPress performance optimization, security hardening, plugin development best practices', tags: ['wordpress', 'performance', 'security', 'php'], install: 'plugin marketplace' },
  { id: 'SpillwaveSolutions/pr-reviewer-skill', name: 'PR Reviewer', author: 'SpillwaveSolutions', repo: 'SpillwaveSolutions/pr-reviewer-skill', category: 'Review', desc: 'Automated PR review skill — code quality, standards, and best practices checks', tags: ['pr', 'review', 'code-quality'], install: 'plugin marketplace' },
  { id: 'levnikolaevich/claude-code-skills', name: 'Pipeline Completo (103 skills)', author: 'levnikolaevich', repo: 'levnikolaevich/claude-code-skills', category: 'Toolkit', desc: '103 skills covering the full development pipeline: planning, coding, testing, deployment', tags: ['pipeline', 'full-stack', 'deployment', 'testing'], install: 'plugin add' },

  // ── ClaudeKit (Marketplace + sub-plugins) ────────────────────────────────
  { id: 'mrgoonie/claudekit-skills', name: 'ClaudeKit Suite', author: 'mrgoonie', repo: 'mrgoonie/claudekit-skills', category: 'Toolkit', desc: 'Complete suite: databases, AI/ML tools, web dev, DevOps, MCP management, auth, repomix', tags: ['databases', 'ai-ml', 'web-dev', 'devops', 'mcp', 'auth'], install: 'plugin marketplace' },
  { id: 'databases@claudekit-skills', name: 'ClaudeKit: Databases', author: 'mrgoonie', repo: 'mrgoonie/claudekit-skills', category: 'Database', desc: 'Database patterns, queries, migrations, optimization — MySQL, PostgreSQL, SQLite, MongoDB', tags: ['sql', 'nosql', 'migrations', 'optimization'], install: 'plugin install databases@claudekit-skills' },
  { id: 'ai-ml-tools@claudekit-skills', name: 'ClaudeKit: AI/ML Tools', author: 'mrgoonie', repo: 'mrgoonie/claudekit-skills', category: 'AI/ML', desc: 'AI/ML integration patterns, model management, data pipelines, prompt engineering', tags: ['ai', 'ml', 'models', 'pipelines'], install: 'plugin install ai-ml-tools@claudekit-skills' },
  { id: 'web-dev-tools@claudekit-skills', name: 'ClaudeKit: Web Dev Tools', author: 'mrgoonie', repo: 'mrgoonie/claudekit-skills', category: 'Web', desc: 'Web development tools: frontend frameworks, APIs, responsive design, accessibility', tags: ['frontend', 'api', 'responsive', 'a11y'], install: 'plugin install web-dev-tools@claudekit-skills' },
  { id: 'devops-tools@claudekit-skills', name: 'ClaudeKit: DevOps Tools', author: 'mrgoonie', repo: 'mrgoonie/claudekit-skills', category: 'DevOps', desc: 'DevOps: CI/CD, Docker, Kubernetes, infrastructure as code, monitoring', tags: ['cicd', 'docker', 'k8s', 'infra'], install: 'plugin install devops-tools@claudekit-skills' },
  { id: 'mcp-management@claudekit-skills', name: 'ClaudeKit: MCP Management', author: 'mrgoonie', repo: 'mrgoonie/claudekit-skills', category: 'MCP', desc: 'Model Context Protocol server management, configuration, and integration patterns', tags: ['mcp', 'servers', 'integration'], install: 'plugin install mcp-management@claudekit-skills' },

  // ── Daymade (Marketplace + sub-plugins) ──────────────────────────────────
  { id: 'daymade/claude-code-skills', name: 'Daymade Suite', author: 'daymade', repo: 'daymade/claude-code-skills', category: 'Toolkit', desc: 'Productivity suite: QA expert, skill creator, GitHub ops, markdown, mermaid, docs', tags: ['qa', 'github-ops', 'markdown', 'mermaid', 'docs'], install: 'plugin marketplace' },
  { id: 'qa-expert@daymade-skills', name: 'Daymade: QA Expert', author: 'daymade', repo: 'daymade/claude-code-skills', category: 'Testing', desc: 'QA expertise: test strategies, test case generation, regression testing, coverage analysis', tags: ['qa', 'testing', 'coverage', 'regression'], install: 'plugin install qa-expert@daymade-skills' },
  { id: 'skill-creator@daymade-skills', name: 'Daymade: Skill Creator', author: 'daymade', repo: 'daymade/claude-code-skills', category: 'Meta', desc: 'Create new Claude Code skills from templates — meta-skill for building your own skills', tags: ['meta', 'skill-creation', 'templates'], install: 'plugin install skill-creator@daymade-skills' },
  { id: 'github-ops@daymade-skills', name: 'Daymade: GitHub Ops', author: 'daymade', repo: 'daymade/claude-code-skills', category: 'Workflow', desc: 'GitHub operations: issue management, PR workflows, release automation, branch policies', tags: ['github', 'issues', 'releases', 'automation'], install: 'plugin install github-ops@daymade-skills' },
  { id: 'markdown-tools@daymade-skills', name: 'Daymade: Markdown Tools', author: 'daymade', repo: 'daymade/claude-code-skills', category: 'Documentation', desc: 'Markdown generation, formatting, table creation, documentation templates', tags: ['markdown', 'docs', 'formatting'], install: 'plugin install markdown-tools@daymade-skills' },
  { id: 'mermaid-tools@daymade-skills', name: 'Daymade: Mermaid Tools', author: 'daymade', repo: 'daymade/claude-code-skills', category: 'Documentation', desc: 'Mermaid diagram generation: flowcharts, sequence diagrams, ERDs, class diagrams', tags: ['mermaid', 'diagrams', 'flowcharts', 'erd'], install: 'plugin install mermaid-tools@daymade-skills' },
  { id: 'ppt-creator@daymade-skills', name: 'Daymade: PPT Creator', author: 'daymade', repo: 'daymade/claude-code-skills', category: 'Documentation', desc: 'PowerPoint presentation creation from code/docs — slides, layouts, content generation', tags: ['ppt', 'presentations', 'slides'], install: 'plugin install ppt-creator@daymade-skills' },
  { id: 'prompt-optimizer@daymade-skills', name: 'Daymade: Prompt Optimizer', author: 'daymade', repo: 'daymade/claude-code-skills', category: 'AI/ML', desc: 'Optimize prompts for better Claude responses — rewriting, testing, scoring prompts', tags: ['prompts', 'optimization', 'ai'], install: 'plugin install prompt-optimizer@daymade-skills' },
  { id: 'statusline-generator@daymade-skills', name: 'Daymade: Statusline Generator', author: 'daymade', repo: 'daymade/claude-code-skills', category: 'Meta', desc: 'Generate Claude Code statusline configurations for project-specific status display', tags: ['statusline', 'config'], install: 'plugin install statusline-generator@daymade-skills' },
  { id: 'claude-code-history-files-finder@daymade-skills', name: 'Daymade: History Files Finder', author: 'daymade', repo: 'daymade/claude-code-skills', category: 'Meta', desc: 'Find and navigate Claude Code conversation history and transcript files', tags: ['history', 'transcripts', 'navigation'], install: 'plugin install claude-code-history-files-finder@daymade-skills' },
  { id: 'docs-cleaner@daymade-skills', name: 'Daymade: Docs Cleaner', author: 'daymade', repo: 'daymade/claude-code-skills', category: 'Documentation', desc: 'Clean and normalize documentation: formatting, broken links, outdated content, consistency', tags: ['docs', 'cleanup', 'formatting'], install: 'plugin install docs-cleaner@daymade-skills' },
  { id: 'claude-md-progressive-disclosurer@daymade-skills', name: 'Daymade: Progressive Disclosure', author: 'daymade', repo: 'daymade/claude-code-skills', category: 'Meta', desc: 'CLAUDE.md progressive disclosure — organize instructions by complexity for better AI comprehension', tags: ['claude-md', 'organization', 'meta'], install: 'plugin install claude-md-progressive-disclosurer@daymade-skills' },

  // ── NPX Install ──────────────────────────────────────────────────────────
  { id: 'jeffallan/claude-skills', name: '66 Skills (12 categories)', author: 'jeffallan', repo: 'jeffallan/claude-skills', category: 'Toolkit', desc: '66 skills in 12 categories: development, testing, security, architecture, DevOps, documentation', tags: ['full-stack', 'security', 'devops', 'architecture'], install: 'npx skills add' },
  { id: 'alirezarezvani/claude-skills', name: 'Domain Expert (53 skills)', author: 'alirezarezvani', repo: 'alirezarezvani/claude-skills', category: 'Architecture', desc: 'System architecture, ADR templates, code review with quality scoring, PR analysis, and 50+ domain expert skills', tags: ['architecture', 'adr', 'review', 'domain-expert'], install: 'npx agent-skills-cli add' },

  // ── Git Clone Skills ─────────────────────────────────────────────────────
  { id: 'QuestForTech-Investments/claude-code-skills', name: 'SQL Expert (MySQL + PostgreSQL + SQLite)', author: 'QuestForTech', repo: 'QuestForTech-Investments/claude-code-skills', category: 'Database', desc: 'SQL expertise: query optimization, schema design, indexing, migrations for MySQL, PostgreSQL, SQLite', tags: ['sql', 'mysql', 'postgresql', 'sqlite', 'optimization'], install: 'git clone' },
  { id: 'VoltAgent/awesome-agent-skills', name: 'WordPress + Supabase Skills', author: 'VoltAgent', repo: 'VoltAgent/awesome-agent-skills', category: 'CMS', desc: 'Official WordPress (10 skills) + Supabase PostgreSQL best practices', tags: ['wordpress', 'supabase', 'postgresql'], install: 'git clone' },
  { id: 'trailofbits/claude-agent-skills', name: 'Trail of Bits Security', author: 'trailofbits', repo: 'trailofbits/claude-agent-skills', category: 'Security', desc: 'Security skills by Trail of Bits: vulnerability analysis, secure coding, audit patterns, threat modeling', tags: ['security', 'audit', 'vulnerabilities', 'threat-modeling'], install: 'git clone' },
  { id: 'darcyegb/ClaudeCodeAgents', name: 'QA Agents', author: 'darcyegb', repo: 'darcyegb/ClaudeCodeAgents', category: 'Testing', desc: 'QA automation agents: test generation, regression detection, coverage analysis, E2E testing', tags: ['qa', 'automation', 'e2e', 'regression'], install: 'git clone' },
  { id: 'affaan-m/everything-claude-code', name: 'Everything Claude Code', author: 'affaan-m', repo: 'affaan-m/everything-claude-code', category: 'Toolkit', desc: 'Hackathon winner — comprehensive Claude Code agents for development, testing, and deployment', tags: ['agents', 'hackathon', 'comprehensive'], install: 'git clone' },
  { id: 'rohitg00/awesome-claude-code-toolkit', name: 'Awesome Toolkit (135 agents + 35 skills)', author: 'rohitg00', repo: 'rohitg00/awesome-claude-code-toolkit', category: 'Toolkit', desc: '135 agents + 35 skills toolkit: development, testing, DevOps, documentation, project management', tags: ['agents', 'toolkit', 'devops', 'docs', 'project-management'], install: 'git clone' },
  { id: 'Interstellar-code/claud-skills', name: 'PHP / Laravel / React Framework', author: 'Interstellar-code', repo: 'Interstellar-code/claud-skills', category: 'Framework', desc: 'Framework skills for PHP, Laravel, and React — patterns, best practices, project scaffolding', tags: ['php', 'laravel', 'react', 'framework'], install: 'git clone' },
  { id: 'alirezarezvani/claude-code-skill-factory', name: 'Skill Factory', author: 'alirezarezvani', repo: 'alirezarezvani/claude-code-skill-factory', category: 'Meta', desc: 'Factory for creating, testing, and publishing your own Claude Code skills', tags: ['meta', 'skill-creation', 'factory', 'publishing'], install: 'git clone' },

  // ── Go / Golang ─────────────────────────────────────────────────────────
  { id: 'mujez/claude-skills', name: 'Go Backend Engineering', author: 'mujez', repo: 'mujez/claude-skills', category: 'Framework', desc: 'Expert Go backend: APIs, concurrency, database patterns, testing, project structure (Go 1.22+)', tags: ['go', 'golang', 'backend', 'concurrency', 'api'], install: 'git clone' },
  { id: 'testcontainers/claude-skills', name: 'Testcontainers Go', author: 'testcontainers', repo: 'testcontainers/claude-skills', category: 'Testing', desc: 'Integration testing with Docker containers for Go — databases, message queues, browsers', tags: ['go', 'golang', 'testing', 'docker', 'integration-tests'], install: 'plugin marketplace' },

  // ── Python ─────────────────────────────────────────────────────────────
  { id: 'ruslan-korneev/python-backend-claude-plugins', name: 'Python Backend (FastAPI + SQLAlchemy)', author: 'ruslan-korneev', repo: 'ruslan-korneev/python-backend-claude-plugins', category: 'Framework', desc: 'Python backend: FastAPI, SQLAlchemy 2.0, Alembic, pytest, modern async patterns', tags: ['python', 'fastapi', 'sqlalchemy', 'async', 'backend'], install: 'plugin marketplace' },
  { id: 'kjnez/claude-code-django', name: 'Django Full Stack (9 skills)', author: 'kjnez', repo: 'kjnez/claude-code-django', category: 'Framework', desc: 'Django completo: models, forms, views, HTMX, Celery, hooks, agents, GitHub Actions', tags: ['python', 'django', 'htmx', 'celery', 'fullstack'], install: 'git clone' },
  { id: 'giuseppe-trisciuoglio/developer-kit', name: 'Developer Kit (Python + React + NestJS + Java)', author: 'giuseppe-trisciuoglio', repo: 'giuseppe-trisciuoglio/developer-kit', category: 'Toolkit', desc: 'Kit modular multi-lenguaje: Python (Django/Flask/FastAPI), React, NestJS, Java/Spring Boot, PHP, AWS', tags: ['python', 'react', 'nestjs', 'java', 'multi-language'], install: 'plugin marketplace' },

  // ── React / Next.js / Frontend ─────────────────────────────────────────
  { id: 'vercel-labs/agent-skills', name: 'React Best Practices by Vercel', author: 'vercel-labs', repo: 'vercel-labs/agent-skills', category: 'Framework', desc: 'Oficial Vercel: 40+ reglas React/Next.js en 8 categorias, priorizadas por impacto en performance', tags: ['react', 'nextjs', 'vercel', 'performance', 'official'], install: 'npx skills add' },
  { id: 'wsimmonds/claude-nextjs-skills', name: 'Next.js Skills (eval boost 32%→78%)', author: 'wsimmonds', repo: 'wsimmonds/claude-nextjs-skills', category: 'Framework', desc: 'Skills Next.js que mejoran pass rate en evals oficiales de Vercel de 32% a 78%', tags: ['nextjs', 'react', 'evals', 'vercel'], install: 'plugin marketplace' },
  { id: 'laguagu/claude-code-nextjs-skills', name: 'Next.js 16 + AI SDK 6', author: 'laguagu', repo: 'laguagu/claude-code-nextjs-skills', category: 'Framework', desc: 'Next.js 16, AI SDK v6, pgvector semantic search, bun, Ralph Loop para apps AI full-stack', tags: ['nextjs', 'react', 'ai-sdk', 'pgvector', 'bun'], install: 'plugin marketplace' },
  { id: 'gocallum/nextjs16-agent-skills', name: 'Next.js 16 + Prisma 7 + AI SDK', author: 'gocallum', repo: 'gocallum/nextjs16-agent-skills', category: 'Framework', desc: 'Migracion Next.js 16, Prisma ORM 7, AI SDK v6 — setup completo para apps modernas', tags: ['nextjs', 'react', 'prisma', 'ai-sdk', 'migration'], install: 'git clone' },
  { id: 'oikon48/cc-frontend-skills', name: 'Frontend UI (Anti-AI Slop)', author: 'oikon48', repo: 'oikon48/cc-frontend-skills', category: 'Design', desc: 'Frontend UI that avoids generic AI aesthetics — bold design decisions with React and Tailwind', tags: ['react', 'tailwind', 'ui', 'design', 'frontend'], install: 'plugin marketplace' },

  // ── Otros skills verificados ─────────────────────────────────────────────
  { id: 'ehmo/platform-design-skills', name: 'Design Rules (300+)', author: 'ehmo', repo: 'ehmo/platform-design-skills', category: 'Design', desc: 'Apple HIG, Material Design 3, WCAG 2.2 — reglas actionables para iOS, Android, Web', tags: ['ui', 'accessibility', 'hig', 'material-design'], install: 'plugin add' },
  { id: 'massimodeluisa/recursive-decomposition-skill', name: 'Recursive Decomposition', author: 'massimo', repo: 'massimodeluisa/recursive-decomposition-skill', category: 'Workflow', desc: 'Descomposicion recursiva para tareas grandes (100+ archivos, 50k+ tokens)', tags: ['large-projects', 'decomposition', 'planning'], install: 'plugin add' },
];

export const SKILL_CATEGORIES = [
  'All', 'Official', 'Engineering', 'Workflow', 'Framework', 'Toolkit',
  'Architecture', 'Database', 'Security', 'Testing', 'Review', 'CMS',
  'AI/ML', 'Web', 'DevOps', 'MCP', 'Documentation', 'Design', 'Meta',
] as const;

export const ALL_SKILLS = [...CORE_SKILLS, ...OPTIONAL_SKILLS];

export function findSkill(id: string): SkillInfo | undefined {
  return ALL_SKILLS.find((s) => s.id === id);
}
